config/routes.rb
Scriba::Engine.routes.draw do
  resources :entries
  resources :requests
end

app/models/scriba/entry.rb
module Scriba
  class Entry
    include Mongoid::Document
    field :severity, type: String
    field :created_at, type: DateTime
    field :message, type: String
    field :user_id, type: Integer

    belongs_to :request, class_name: "Scriba::Request"

    def self.log(severity, time, progname, message)
      collection.insert(request_id: Thread.current[:scriba_request_id],
                        severity: severity,
                        created_at: time,
                        message: message,
                        user_id:  Thread.current[:scriba_user_id]) unless Thread.current[:in_scriba]
    end


    delegate :user, :user_path, to: :request
  end
end

app/models/scriba/request.rb
module Scriba
  class Request
    include Mongoid::Document
    field :env, type: Hash
    field :response_status, type: Integer
    field :response_headers, type: Hash
    field :response_body, type: String
    field :user_id, type: String
    has_many :entries, class_name: "Scriba::Entry"

    def self.log(env)
      Thread.current[:scriba_request_id] = nil
      Thread.current[:scriba_user_id] = nil

      request = new(env: prepare_hash(env))

      Thread.current[:in_scriba] = !!(request.env["PATH_INFO"] =~ /scriba/)

      request.save unless Thread.current[:in_scriba]

      Thread.current[:scriba_request_id] = request.id
      Thread.current[:scriba_user_id] = request.user.try(:id)

      resp = yield env
      request.update_attributes response_status: resp[0],
                                response_headers: resp[1],
                                response_body: if Scriba.log_response_body &&
                                                  resp[2].respond_to?(:body) &&
                                                  resp[2].body.respond_to?(:encoding) &&
                                                  resp[2].body.try(:encoding).try(:name) == "UTF-8"
                                                 resp[2].body
                                               else
                                                 # resp[2].to_s
                                               end,
                                user_id: request.user.try(:id)
      resp
    end

    def self.prepare_hash(hash)
      unless hash.kind_of?(Hash)
        begin
          BSON::serialize(hash)
          return hash
        rescue
          return hash.to_s
        end
      end

      return Hash[
        hash.select {
          |k,v|
          v.kind_of?(String) || v.kind_of?(Numeric) ||
          v.kind_of?(TrueClass) || v.kind_of?(FalseClass) ||
          v.kind_of?(Hash)
        }.map {|k,v| [k.to_s.gsub(".", "_dot_"), prepare_hash(v)] }
      ]
    end

    def path
      env["PATH_INFO"]
    end

    def user
      if Scriba.user_finder.respond_to?(:call)
        Scriba.user_finder.call(env)
      else
        nil
      end
    end

    def user_path
      if Scriba.user_path_finder.respond_to?(:call)
        Scriba.user_path_finder.call(user)
      else
        ""
      end
    end
  end
end

app/controllers/scriba/application_controller.rb
module Scriba
  class ApplicationController < ActionController::Base
    before_filter :auth

    private

    def auth
      Scriba.auth_handler.bind(self).call if Scriba.auth_handler.is_a? Proc
    end
  end
end

app/controllers/scriba/entries_controller.rb
class Scriba::EntriesController < Scriba::ApplicationController
  def index
    @from = begin
              Time.parse(params[:from])
            rescue Exception => e
              nil
            end

    @to = begin
            Time.parse(params[:to])
          rescue Exception => e
            nil
          end

    @entries = Scriba::Entry.order_by([:created_at, :desc])

    if @from
      @entries = @entries.where("created_at" => {"$gt" => @from})
    end

    if @to
      @entries = @entries.where("created_at" => {"$gt" => @to})
    end

    @user_id = if params[:user_id].present?
                 params[:user_id].to_i
               else
                 nil
               end

    if @user_id
      @entries = @entries.where("user_id" => @user_id)
    end

    @severity = params[:severity] if params[:severity].present?

    if @severity
      @entries = @entries.where("severity" => @severity)
      if @severity == "ERROR"
        selector = @entries.selector
        map = 'function() { emit(this.message, {count: 1}) };'
        reduce = 'function(message, values) { var result = 0; values.forEach(function(value) { result += 1 }); return result};'
        Scriba::Entry.collection.map_reduce map, reduce,
          query: selector,
          out: {replace: "scriba_report_items"}
        @report = Scriba::Entry.db.collection("scriba_report_items").find().to_a.map { |item|
          unless item["value"].is_a?(Hash)
            item["value"] = {"count" => item["value"]}
          end
          item
        }.sort {|a,b|
          b["value"]["count"] <=> a["value"]["count"]}
      end
    end

    @entries = @entries.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/scriba/requests_controller.rb
class Scriba::RequestsController < Scriba::ApplicationController
  def show
    @request = Scriba::Request.find params[:id]
  end
end

app/helpers/scriba/application_helper.rb
module Scriba
  module ApplicationHelper
  end
end

app/views/layouts/scriba/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scriba</title>
  <%= stylesheet_link_tag    "scriba/application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="container">
    <%= yield %>
  </div>
  <div id="footer">
    <div id="shameless">
      Brought to you by <%= link_to "AmberBit", "http://amberbit.com" %> Ruby on Rails web development team.
      <br/>
      2010-2011 &copy; Hubert Łępicki &lt;hubert.lepicki@amberbit.com&gt;
    </div>
    <%= link_to image_tag("http://amberbit.com/images/logo.png"), "http://amberbit.com" %>
  </div>
</html>

app/views/scriba/entries/index.html.haml
%h1
  Log entries
  = "(#{@entries.total_entries} in total)"


= form_tag entries_path, method: "get" do
  = text_field_tag :from, @from.to_s, placeholder: "YYYY-MM-DD HH:MM:SS"
  = text_field_tag :to, @to.to_s, placeholder: "YYYY-MM-DD HH:MM:SS"
  = text_field_tag :user_id, @user_id, placeholder: "User ID"
  = select_tag :severity, options_for_select([["Any Severity", nil], ["INFO", "INFO"], ["DEBUG", "DEBUG"], ["WARN", "WARN"], ["ERROR", "ERROR"], ["FATAL", "FATAL"]], @severity)
  = submit_tag "Filter results"

- if @report.present?
  %h3 Overall report
  %table.table.table-striped
    %thead
      %tr
        %th
          Count
        %th
          Message(s)
    %tbody
      - @report.each do |item|
        %tr
          %td= item["value"]["count"].to_i
          %td= item["_id"]

  %h3 Log entries

= will_paginate @entries

%table.table.table-striped
  %thead
    %tr
      %th.overview
        Request overview
      %th.timestamp
        Timestamp
      %th
        Type
      %th
        Message

  %tbody
    - @entries.each do |entry|
      %tr
        %td
          ID:
          = link_to entry.request_id.to_s, entry.request
          %br
          User:
          = link_to(entry.user.id, entry.user_path, target: "_parent") if entry.request && entry.user_path != ""
          %br
          Page:
          = link_to(entry.request.path, entry.request.path, target: "_parent") if entry.request && entry.request.path
        %td= entry.created_at.to_s(:db)
        %td= entry.severity
        %td= truncate(entry.message, length: 1000)

%div{style: "clear: both"}
= will_paginate @entries

app/views/scriba/requests/show.html.haml
%h1 Request log

%h3 Request/cookie/session details
= debug @request.env

%h3 Response status
= @request.response_status

%h3 Response headers
= @request.response_headers

%h3 Response body
%pre
  = @request.response_body

%h3 Log entries

%table.table.table-striped
  %thead
    %tr
      %th
        Timestamp
      %th
        Type
      %th
        Message

  %tbody
    - @request.entries.each do |entry|
      %tr
        %td= entry.created_at.to_s(:db)
        %td= entry.severity
        %td= entry.message